try:
    print('try')
except:
    print('except')
finally:
    print('finally')

"""Example Four"""
try:
    num = 5/0
except:
    print("An error")
    raise



"""Example Two"""
try:
    print('try', name)
except:
    print(unknow_var)
finally:
    print('ok')

    

"""Example Three"""
name = "123"
raise NameError("This is name error")

